dataset_management/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('tasks/', include('task_app.urls')),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
]

task_app/urls.py
from django.urls import path
from . import views

app_name = "task_app"
urlpatterns = [
    path('', views.IndexView.as_view(), name='task'),
    path('<int:pk>/', views.DetailView.as_view(), name="detail"),
    path('book/<int:TaskId>', views.Booking, name="booking"),
    path('revoke/<int:TaskId>', views.Revoke, name="revoking"),
    path('download/<int:TaskId>', views.Download, name="download"),
    path('delete/<int:TaskId>', views.Delete, name="delete"),
    path('new-task/', views.NewTask, name="new_task"),
    path('new-task/upload', views.NewTaskUpload, name="upload_handler"),
]

task_app/models.py
from django.db import models

# Create your models here.
class Tasks(models.Model):
    Title = models.CharField("Title",max_length=500)   
    BookedByUser = models.CharField("Booked By", max_length=500)
    UploadDate = models.DateTimeField("Uploaded At")
    isDeleted = models.BooleanField("Is Deleted", default=False)

    def __str__(self):
        return self.Title
    
class TasksZipFile(models.Model):
    Title = models.ForeignKey(Tasks, on_delete=models.CASCADE)    
    ZIPFile = models.FileField("File Name", upload_to='ZIPFiles/%Y-%m')

task_app/forms.py
from django import forms

class UploadFileForm(forms.Form):
    title = forms.CharField(max_length=100)
    file = forms.FileField(label='Upload Task\'s File')

task_app/views.py
from task_app.models import Tasks, TasksZipFile
from django.http import FileResponse
from django.shortcuts import get_object_or_404, render
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic
from django.utils import timezone
from .forms import UploadFileForm
# for zipfile upload

class IndexView(LoginRequiredMixin, generic.ListView):
    template_name = 'task_app/task.html'
    context_object_name = "TaskList"
    
    def get_queryset(self):        
        return Tasks.objects.filter(isDeleted=False).order_by('UploadDate')

class DetailView(LoginRequiredMixin, generic.DetailView):
    model = Tasks
    template_name = "task_app/detail.html"

@login_required
def NewTask(request):
    form = UploadFileForm()
    context={'form':form}
    return render(request, 'task_app/new_task.html', context)

@login_required
def NewTaskUpload(request):    
    try:        
        Form = UploadFileForm(request.POST, request.FILES)
        if Form.is_valid():
            File = request.FILES['file']
            FileName = request.FILES['file'].name
            
            if FileName.endswith('.zip'):
                TaskTitle = request.POST['title']
                NewTask = Tasks(Title=TaskTitle, UploadDate=timezone.now(), isDeleted=False)
                NewTask.save()

                NewTaskZip = TasksZipFile(Title=NewTask, ZIPFile=File)
                NewTaskZip.save()
            else:
                return render(request, 'task_app/error_handler.html', {
                    "error_message": "You have to upload a zip file."
                })
    except (KeyError):
        return render(request, 'task_app/error_handler.html', {
            "error_message": "Error occured"
        })
    return render(request, 'task_app/error_handler.html', {
        "TaskTitle": TaskTitle, "Filename": FileName
    })

@login_required
def Booking(request, TaskId):
    try:        
        BookingTask = get_object_or_404(Tasks, pk=TaskId)
        if request.user.is_authenticated:
            Username = request.user.username
            BookingTask.BookedByUser = Username
            BookingTask.save()
            BookSuccess = True
    except (KeyError, Tasks.DoesNotExist):
        return render(request, 'task_app/error_handler.html', {
            "error_message": "Error occured"
        })
    return render(request, 'task_app/error_handler.html', {
        "Username": Username, "Booked": BookSuccess
    })

@login_required
def Revoke(request, TaskId):
    try:        
        RevokingTask = get_object_or_404(Tasks, pk=TaskId)
        if request.user.is_authenticated:
            Username = request.user.username
            if Username == RevokingTask.BookedByUser:
                RevokingTask.BookedByUser = ""
                RevokingTask.save()
                RevokeSuccess = True
            else:
                return render(request, 'task_app/error_handler.html', {
                    "error_message": "You don't have permission to revoke this task"
                })
    except (KeyError, Tasks.DoesNotExist):
        return render(request, 'task_app/error_handler.html', {
            "error_message": "Error occured"
        })
    return render(request, 'task_app/error_handler.html', {
        "Revoke" : RevokeSuccess
    })

@login_required
def Download(request, TaskId):
    try:        
        DownloadTask = get_object_or_404(Tasks, pk=TaskId)        
        if request.user.is_authenticated:
            Username = request.user.username

        if Username == DownloadTask.BookedByUser:        
            DownloadTaskFile = get_object_or_404(TasksZipFile, Title=DownloadTask)
            FilePath = DownloadTaskFile.ZIPFile.path
            Response = FileResponse(open(FilePath, 'rb'))
            return Response
        else:
            return render(request, 'task_app/error_handler.html', {
                "error_message": "You don't have permission to download this file."
            })
    except (KeyError, Tasks.DoesNotExist):
        return render(request, 'task_app/error_handler.html', {
            "error_message": "Error occured"
        })

@login_required
def Delete(request, TaskId):
    try:        
        DeleteTask = get_object_or_404(Tasks, pk=TaskId)
        if request.user.is_authenticated:
            Username = request.user.username

        if Username == DeleteTask.BookedByUser:
            DeleteTask.isDeleted = True
            DeleteTask.save()
            Deleted = True
        else:
            return render(request, 'task_app/error_handler.html', {
                "error_message": "You don't have permission to delete this task."
            })

    except (KeyError, Tasks.DoesNotExist):
        return render(request, 'task_app/error_handler.html', {
            "error_message": "Error occured"
        })
    return render(request, 'task_app/error_handler.html', {
        "Deleted": Deleted
    })
    

task_app/templates/base.html
<html>
  <head>
    <meta charset="utf-8" />
    <title>Dataset Management Platform {% block title %}{% endblock %}</title>
    {% load static %}
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'task_app/style.css' %}"
    />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300&display=swap"
      rel="stylesheet"
    />
  </head>
  <body>
    <header>
      <div class="header-name">
      <a href="{% url 'home' %}" class="home-btn">
        <h1>Dataset Management Platform</h1>
      </a>         
      </div>
      <div class="header-content">
        {% if user.is_authenticated %}
          <p>Hi, {{ user.username }}!</p>
          <a href="{% url 'logout' %}" class="header-logout">Log Out</a>
        {% endif %}
      </div>
    </header>

    {% block content %} 
    {% endblock %}
    
    <footer>
      <h5>
        Created By David Liois Jayadi © 2021
      </h5>
    </footer>
  </body>
</html>

task_app/templates/home.html
{% extends 'base.html' %} 

{% block title %}- Home Page{% endblock %} 

{% block content %}

<section>
  {% if user.is_authenticated %}
    <div class="auth">
      <a href="{% url 'task_app:new_task' %}">New Tasks</a>
      <a href="{% url 'task_app:task' %}">Tasks</a>
    </div>
  {% else %}
    <div class="notauth">
      <p>You are not logged in</p>    
      <a href="{% url 'login' %}">Log In</a>    
    </div>
  {% endif %}
</section>

{% endblock %}

task_app/templates/task_app/detail.html
{% extends 'base.html' %}

{% block content %}

<section>        
    <div class="detail">
        <h1>Tasks Detail</h1>
        <table class="table">
            <tr>
                <th>Task Title</th>
                <th>Booked By</th>
                <th>Upload Date</th>                
                <th>Action</th>
            </tr>                                                     
            <tr>
                <td>{{ tasks.Title }}</td>  
                <td>{{ tasks.BookedByUser }}</td>
                <td>{{ tasks.UploadDate }}</td>                
                {% if tasks.BookedByUser %}
                    <td>
                        <a href="{% url 'task_app:revoking' tasks.id%}" class="btn">Revoke</a>
                        <a href="{% url 'task_app:download' tasks.id%}" class="btn">Download</a>
                        <a href="{% url 'task_app:delete' tasks.id%}" class="btn">Delete</a>
                    </td>                    
                {% else %}
                    <td><a href="{% url 'task_app:booking' tasks.id%}" class="btn book-btn">Book</a></td>                    
                {% endif %}            
            </tr>            
        </table>                    
        <a href="{% url 'task_app:task' %}" class="login-btn">Back</a>
    </div>
</section>

{% endblock %}

task_app/templates/task_app/error_handler.html
{% extends 'base.html' %}

{% block content %}

<section>        
    <div class="handler">
        {% if error_message %}
            <h2>Task Operation Failed</h2>
            <h3>{{error_message}}</h3>
            <a href="{% url 'task_app:task' %}" class="login-btn">Back</a>    
        {% endif %}
        {% if TaskTitle %}
            <h2>New Task Successfully Added</h2>
            <h3>Title : {{ TaskTitle }}</h3>
            <h3>Filename : {{ Filename }}</h3>
            <a href="{% url 'task_app:task' %}" class="login-btn">Home</a>    
        {% endif %}
        {% if Booked %}
            <h2>Task Booked</h2>
            <h3>Booked By : {{ Username }}</h3>     
            <a href="{% url 'task_app:task'%}" class="login-btn">Back</a> 
        {% endif %}
        {% if Revoke %}
            <h2>Task Revoked</h2>            
            <a href="{% url 'task_app:task'%}" class="login-btn">Back</a> 
        {% endif %}
        {% if Deleted %}
            <h2>Task Deleted</h2>
            <a href="{% url 'task_app:task'%}" class="login-btn">Back</a> 
        {% endif %}
    </div>
</section>

{% endblock %}

task_app/templates/task_app/new_task.html
{% extends 'base.html' %}

{% block title %}- Login{% endblock %}

{% block content %}

<section>
    <div class="new-task-form">        
        <form action="{% url 'task_app:upload_handler' %}" method="post" enctype="multipart/form-data">
            <h2>New Task</h2>
            {% csrf_token %}
            {{form.title.label_tag}} {{form.title}}
            {{form.non_field_errors}}
    
            {{ form.file.label_tag }} 
            {{ form.file.help_text }}
            {{ form.file.errors }}{{ form.file }}                           
            <button class="login-btn" type="submit" style="margin: 20px;">Add</button>             
        </form>
        <a href="{% url 'task_app:task' %}" class="login-btn">Back</a>   
        <a href="{% url 'home' %}" class="login-btn">Home</a>            
    </div>    
</section>

{% endblock %}

task_app/templates/task_app/task.html
{% extends 'base.html' %}

{% block title %}- Task{% endblock %}

{% block content %}

<section>
    <div class="task-list">
        <h1>Tasks List</h1>
        {% if TaskList %} 
            <table class="table">
                <tr>
                    <th>Task Title</th>
                    <th>Booked By</th>                       
                </tr>             
                {% for task in TaskList %}                            
                    <tr>
                        <td><a href="{% url 'task_app:detail' task.id %}">{{ task.Title }}</a></td>  
                        <td>{{ task.BookedByUser }}</td>                                                
                    </tr>
                {% endfor %}  
            </table>                               
        {% else %}
            <h3>No tasks are available.</h3>
        {% endif %}
        <a href="{% url 'task_app:new_task' %}" class="login-btn">New Tasks</a>
        <a href="{% url 'home' %}" class="login-btn">Home</a>
    </div>
</section>

{% endblock %}